apiVersion: v1
kind: Pod
metadata:
  name: nexus-pod
  labels:
    app: nexus
spec:
  containers:
    - name: cont1
      image: sonatype/nexus3
      ports:
        - containerPort: 8081
      volumeMounts:
        - name: vol1
          mountPath: /nexus-data
  tolerations:
    - key: node
      operator: Equal
      value: nexus
      effect: NoSchedule
    - key: node
      operator: Equal
      value: nexus
      effect: NoExecute
  nodeSelector:
    node: nexus
  volumes:
    - name: vol1
      hostPath:
        path: /data/nexus
        type: DirectoryOrCreate
