apiVersion: v1
kind: Service
metadata:
  name: sonar-svc
spec:
  type: NodePort
  selector:
    app: sonarqube
  ports:
    - name: http
      targetPort: 9000
      nodePort: 30002
      port: 30001
