apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app-config
  namespace: argocd
spec:
  project: calculator-java
  source:
    repoURL: https://github.com/jayanthis952/calculator-java-gitops.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: project
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

